
configs:
  player_name: ${UNKNOWN_PLAYER_NAME:Unknown}
  show_price: ${SHOW_PRICE:false}
  db:
    shop:
      type: ${SHOP_DB_TYPE:postgresql}
      host: ${SHOP_DB_HOST:localhost:5432}
      name: ${SHOP_DB_NAME:quickshop}
      user: ${SHOP_DB_USER:postgres}
      password: ${SHOP_DB_PASSWORD:Qwerty}
    player:
      type: ${PLAYER_DB_TYPE:postgresql}
      host: ${PLAYER_DB_HOST:localhost:5432}
      name: ${PLAYER_DB_NAME:luckperms}
      user: ${PLAYER_DB_USER:postgres}
      password: ${PLAYER_DB_PASSWORD:Qwerty}

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# shop database
shop:
  datasource:
    jdbc-url: jdbc:${configs.db.shop.type}://${configs.db.shop.host}/${configs.db.shop.name}
    username: ${configs.db.shop.user}
    password: ${configs.db.shop.password}

# player database
player:
  datasource:
    jdbc-url: jdbc:${configs.db.player.type}://${configs.db.player.host}/${configs.db.player.name}
    username: ${configs.db.player.user}
    password: ${configs.db.player.password}
