
configs:
  player_name: ${UNKNOWN_PLAYER_NAME:Unknown}
  show_price: ${SHOW_PRICE:false}
  db:
    type: ${DB_TYPE:postgresql}
    host: ${DB_HOST:localhost:5432}
    name: ${DB_NAME:postgres}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:Qwerty}

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:${configs.db.type}://${configs.db.host}/${configs.db.name}
    username: ${configs.db.user}
    password: ${configs.db.password}

