
UNKNOWN_PLAYER_NAME: Unknown

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

# shop database
shop:
  datasource:
    jdbc-url: jdbc:mariadb://localhost:3306/quickshop
    username: username
    password: Qwerty

# player database
player:
  datasource:
    jdbc-url: jdbc:mariadb://localhost:3306/luckperms
    username: username
    password: Qwerty
