
UNKNOWN_PLAYER_NAME: Unknown
SHOW_PRICE: false

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# shop database
shop:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/quickshop
    username: postgres
    password: Qwerty

# player database
player:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/luckperms
    username: postgres
    password: Qwerty
