
configs:
  player_name: ${UNKNOWN_PLAYER_NAME:Unknown}
  show_price: ${SHOW_PRICE:false}
  db:
    type: ${DB_TYPE:sqlite}
    name: ${DB_NAME:data.db}
    user: ${DB_USER:username}
    password: ${DB_PASSWORD:password}

spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.SQLiteDialect
  datasource:
    url: jdbc:${configs.db.type}:${configs.db.name}
    username: ${configs.db.user}
    password: ${configs.db.password}
